baseURL = 'https://daemotron.github.io/'
languageCode = 'en-gb'
title = 'My Universe'
theme = 'puppet'
enableEmoji = true
enableInlineShortcodes = true
paginate = 5

[params]
author = "daemotron"
description = "Mens Insana in Corpore Ignavo"
keywords = "blog,developer,personal"
img_home = "img/home-bg.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = false

[params.social]
github = "daemotron"
gitlab = "daemotron"
linkedin = "jescofreund"
stackoverflow = "5217009/daemotron"
rss = true

[permalinks]
posts = '/:year/:month/:day/:title/'

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/daemotron/daemotron.github.io/"
weight = 100
