baseURL = 'https://www.my-universe.com/'
languageCode = 'en-gb'
title = 'My Universe'
theme = 'bilberry-hugo-theme'
enableEmoji = true
enableInlineShortcodes = true

#paginate = 5

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # let hugo automatically resize and crop your images to the correct sizes
  resizeImages = true

  # Description and meta data for the search engines
  author = "daemotron"
  description = "Mens Insana in Corpore Ignavo"
  subtitle = "Mens Insana in Corpore Ignavo"
  keywords = "blog,developer,personal"

#img_home = "img/home-bg.jpg"
#img_404 = "img/404-bg.jpg"
  
  # set an path to the image file you want to use | overwrites avatar by email
  customImage = "/img/avataaars.png"

  # define the icon you want to use for the overlay for the customImage or avatar.
  overlayIcon = "fa-home"

  # always display the top navigation (with pages and search) on non-mobile screens
  permanentTopNav = false

  # always display the top navigation when scrolling
  # works only with permanentTopNav = true
  stickyNav = false

  # show a language chooser in the header
  showHeaderLanguageChooser = true

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # enable highlight.js for syntax highlighting or (if set to false) use
  # the hugo built-in chroma highlighter
  enableHighlightJs = true

  # enable automatic localization of the article's PublishedDate with momentjs
  enableMomentJs = true

  # Enable / Disable algolia search
  algolia_search    = false
  algolia_appId     = "OWMLA6LB4S"
  algolia_apiKey    = "83dfd646c2c7d94662d0edb6f9d319e9"
  algolia_indexName = "index"
  # Set this option to false if you want to search within all articles in all languages at once
  algolia_currentLanguageOnly = true

  # customize the date format | only works if momentjs is disabled | only works with English month names
  # you can customize it with the options you find here:
  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02"

  # display the estimated reading time for an article
  showReadingTime = false

  # Minimum word count to display the Table of Contents
  tocMinWordCount = 400

  # Footer configuration
  showFooter = true

  # How many articles should be displayed at latest posts in the footer?
  # Set to -1 to hide the 'Latest Posts' column
  amountLatestPostsInFooter = 7

  # How many categories should be displayed in the footer section?
  # Set to -1 to hide the 'Categories' column
  amountCategoriesInFooter = 7

  # show a language chooser in the footer
  showFooterLanguageChooser = true

  # social media profile urls for the footer links
  showSocialMedia = true

  # define your links with FontAwesome 5 (only free icons are supported)
  # all icons https://fontawesome.com/icons?d=gallery&m=free
  # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
  socialMediaLinks = [
    { link = "https://github.com/daemotron", icon = "fab fa-github" },
    { link = "https://gitlab.com/daemotron", icon = "fab fa-gitlab" },
    { link = "https://stackoverflow.com/users/5217009/daemotron", icon = "fab fa-stack-overflow", rel = "me" },
    { link = "https://www.linkedin.com/in/jescofreund", icon = "fab fa-linkedin" },
    { link = "/index.xml", icon = "fas fa-rss" },
  ]

  # show an archive link in the footer
  showArchive = true

  # archive grouping: "2006" by year, "2006-01" by month
  archiveDateGrouping = "2006-01"

  # credits line configuration
  copyrightBy = "My Universe"
  copyrightUseCurrentYear = false  # set to true to always display the current year in the copyright
  copyrightYearOverride = "2017"
  copyrightUrl = "https://www.my-universe.com/"
  creditsText = "Powered by Hugo & Bilberry Hugo Theme"
  creditsUrl = "https://gohugo.io/"

  useFaviconGenerator = true

[params.social]
github = "daemotron"
gitlab = "daemotron"
linkedin = "jescofreund"
stackoverflow = "5217009/daemotron"
rss = true

[permalinks]
posts = '/:year/:month/:day/:title/'
gallery = '/:year/:month/:day/:title/'

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "author"

[outputs]
home = [ "HTML", "JSON", "RSS" ]
page = [ "HTML" ]

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/daemotron/daemotron.github.io/"
weight = 100
