= Reboot 
// :published_at: 2019-01-31
:hp-tags: Blog, Open_Source,

[.lead]
I amar prestar aen, +
Han mathon ne nen, +
Han mathon ne chae +
A han noston ned 'wilith

And again, my world is changing. A bit more than one year ago, I moved from a self-hosted blog built with https://ghost.org/[Ghost] to a fully managed website using Jimdo's website construction kit. Sure, the effort for maintaining the full stack (server, os, database, webserver software, etc.) has gone, and I certainly don't want it back.

But maintaining the website itself has proven to be a bit of a hassle with Jimdo -- each page, even each blog post, has to be bricolaged together with predefined content elements. So a lot of my time spent on the website went into layouting articles, instead of writing content. Other than with Ghost, you couldn't just log in and write away in simple plain text (https://en.wikipedia.org/wiki/Markdown[Markdown], to be precise).

This really had an impact on my posting frequency -- at some time, it was as low as just once every couple of months (my personal "best" was a full 5 months of silence). Not being happy with Jimdo (mostly due to that), I constantly kept looking for alternate solutions, that would give me back an easier content creation, but not at the cost of making me spend hours on administrating servers and applications again.

I tried some big CMS stuff (like https://plone.org/[Plone 5], https://www.django-cms.org/[django CMS], http://www.opencms.org/[OpenCms] and http://www.ametys.org/[Ametys]) hosted on managed cloud services, but again I didn't find the simplicity I was hoping for. Either it was very complex to set up the site itself, or blogging in general was not well supported. Or media management proved to be complex, or inserting syntax-highlighted code snippets into articles was impossible without bigger hacks... just chose, none of them had real simplicity and elegance in store.